// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: contant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteType int32

const (
	RouteType_DIRECT RouteType = 0 //直达
	RouteType_RULE   RouteType = 1 // 规则
	RouteType_GROUP  RouteType = 2 // 群组
)

// Enum value maps for RouteType.
var (
	RouteType_name = map[int32]string{
		0: "DIRECT",
		1: "RULE",
		2: "GROUP",
	}
	RouteType_value = map[string]int32{
		"DIRECT": 0,
		"RULE":   1,
		"GROUP":  2,
	}
)

func (x RouteType) Enum() *RouteType {
	p := new(RouteType)
	*p = x
	return p
}

func (x RouteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteType) Descriptor() protoreflect.EnumDescriptor {
	return file_contant_proto_enumTypes[0].Descriptor()
}

func (RouteType) Type() protoreflect.EnumType {
	return &file_contant_proto_enumTypes[0]
}

func (x RouteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteType.Descriptor instead.
func (RouteType) EnumDescriptor() ([]byte, []int) {
	return file_contant_proto_rawDescGZIP(), []int{0}
}

var File_contant_proto protoreflect.FileDescriptor

var file_contant_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x2c, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x52, 0x55, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x4f,
	0x55, 0x50, 0x10, 0x02, 0x42, 0x11, 0x5a, 0x0f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contant_proto_rawDescOnce sync.Once
	file_contant_proto_rawDescData = file_contant_proto_rawDesc
)

func file_contant_proto_rawDescGZIP() []byte {
	file_contant_proto_rawDescOnce.Do(func() {
		file_contant_proto_rawDescData = protoimpl.X.CompressGZIP(file_contant_proto_rawDescData)
	})
	return file_contant_proto_rawDescData
}

var file_contant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contant_proto_goTypes = []interface{}{
	(RouteType)(0), // 0: proto.RouteType
}
var file_contant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contant_proto_init() }
func file_contant_proto_init() {
	if File_contant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contant_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contant_proto_goTypes,
		DependencyIndexes: file_contant_proto_depIdxs,
		EnumInfos:         file_contant_proto_enumTypes,
	}.Build()
	File_contant_proto = out.File
	file_contant_proto_rawDesc = nil
	file_contant_proto_goTypes = nil
	file_contant_proto_depIdxs = nil
}
